#!/bin/bash

export PATH=`pwd`/../../../prebuilt/linux-x86/toolchain/arm-eabi-4.4.0/bin/:$PATH

export KERNEL_DIR=../../../kernel/msm/
export ARCH=arm
export CROSS_COMPILE=arm-eabi-

if [ ! -n "${1+1}" ]; then
    NUMPROC=1
else
    NUMPROC=$1
fi

nice make -j$NUMPROC
